-- 1. Users Table (Extends Supabase Auth)
create table users (
  id uuid references auth.users not null primary key,
  full_name text not null,
  phone text unique,
  role text default 'customer' check (role in ('customer', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Categories (e.g., "Birthdays", "Anniversaries", "Flowers")
create table categories (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ar text not null,
  image_url text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Products (Gifts)
create table products (
  id bigint generated by default as identity primary key,
  category_id bigint references categories(id) on delete set null,
  name_en text not null,
  name_ar text not null,
  desc_en text,
  desc_ar text,
  price numeric(10,2) not null,
  stock_quantity integer default 0,
  is_active boolean default true,
  image_url text,
  is_customizable boolean default false, -- If true, user can add custom text
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Orders (Modified for Gift Logic)
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  status text default 'pending_payment' check (status in ('pending_payment', 'processing', 'out_for_delivery', 'completed', 'cancelled')),
  total_amount numeric(10,2) not null,
  delivery_fee numeric(10,2) default 0,
  payment_method text not null check (payment_method in ('cash', 'instapay')),
  
  -- Delivery Details
  delivery_type text not null check (delivery_type in ('pickup', 'delivery')),
  delivery_address text,
  recipient_phone text, -- In case the gift is for someone else
  scheduled_delivery_date date, -- Crucial for gifts
  
  -- Payment Proof
  payment_proof_url text, 
  
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Order Items
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade,
  product_id bigint references products(id),
  quantity integer not null,
  price_at_purchase numeric(10,2) not null,
  
  -- Gift Specific Options
  gift_message text, -- "Happy Birthday Mom!"
  is_wrapped boolean default false
);

-- 6. Cart (Persistent)
create table cart (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  product_id bigint references products(id),
  quantity integer default 1,
  gift_message text,
  is_wrapped boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, product_id)
);

-- Indexes for Performance
create index users_phone_idx on users (phone);
create index products_category_id_idx on products (category_id);
create index orders_user_id_idx on orders (user_id);
