-- 1. Users Table (Extends Supabase Auth)
create table users (
  id uuid references auth.users not null primary key,
  full_name text not null,
  phone text,
  email text,
  role text default 'customer' check (role in ('customer', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Categories (e.g., "Birthdays", "Anniversaries", "Flowers")
create table categories (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ar text not null,
  image_url text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Products (Gifts)
create table products (
  id bigint generated by default as identity primary key,
  category_id bigint references categories(id) on delete set null,
  name_en text not null,
  name_ar text not null,
  desc_en text,
  desc_ar text,
  price numeric(10,2) not null,
  sale_price numeric(10,2),
  sale_end_date timestamp with time zone,
  is_active boolean default true,
  in_stock boolean default true,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Orders (Modified for Gift Logic)
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  status text default 'processing' check (status in ('pending_payment', 'processing', 'out_for_delivery', 'ready_for_pickup', 'completed', 'cancelled')),
  total_amount numeric(10,2) not null,
  delivery_fee numeric(10,2) default 0,
  payment_method text not null check (payment_method in ('cash', 'instapay')),
  
  -- Delivery Details
  delivery_type text not null check (delivery_type in ('pickup', 'delivery')),
  delivery_address text,
  phone text, -- Contact phone for delivery
  delivery_date date, -- Scheduled delivery date
  
  -- Payment Proof
  payment_proof_url text, 
  
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Order Items
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade,
  product_id bigint references products(id),
  quantity integer not null,
  price_at_purchase numeric(10,2) not null,
  
  -- Gift Specific Options
  gift_message text, -- "Happy Birthday Mom!"
  is_wrapped boolean default false
);

-- 6. Cart (Persistent)
create table cart (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  product_id bigint references products(id),
  quantity integer default 1,
  gift_message text,
  is_wrapped boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, product_id)
);

-- 7. User Addresses
create table user_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  label text not null, -- "Home", "Work", etc.
  address text not null,
  is_default boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 8. Store Settings
create table store_settings (
  id bigint primary key default 1,
  store_name text not null,
  description text,
  phone text,
  phone_2 text,
  phone_3 text,
  email text,
  address text,
  
  -- Currency Settings
  currency text default 'EGP',
  currency_code text not null default 'EGP',
  currency_symbol text not null default 'EGP',
  
  -- Delivery Settings
  delivery_fee numeric(10,2) default 25.00,
  free_delivery_threshold numeric(10,2),
  delivery_time_days text default '1-3 business days',
  
  -- Payment Settings
  instapay_enabled boolean default true,
  instapay_phone text default '01000000000',
  
  -- Store Info
  working_hours text default 'Sunday - Thursday: 9:00 AM - 9:00 PM',
  hero_image_url text default '/hero-image.jpg',
  active_theme text not null default 'default',
  
  -- Social Media
  facebook_url text,
  instagram_url text,
  twitter_url text,
  linkedin_url text,
  
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  
  -- Ensure only one settings row
  constraint store_settings_singleton check (id = 1)
);

-- Indexes for Performance
create index users_phone_idx on users (phone);
create index products_category_id_idx on products (category_id);
create index orders_user_id_idx on orders (user_id);
create index user_addresses_user_id_idx on user_addresses (user_id);
