-- Create user_addresses table for storing multiple addresses per user
create table if not exists user_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) on delete cascade not null,
  label text not null, -- e.g., 'Home', 'Work', 'Default'
  address text not null,
  is_default boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create index for faster lookups
create index user_addresses_user_id_idx on user_addresses(user_id);

-- Ensure only one default address per user
create unique index user_addresses_user_id_default_idx 
on user_addresses(user_id) 
where is_default = true;

-- RLS Policies
alter table user_addresses enable row level security;

-- Users can only see their own addresses
create policy "Users can view their own addresses"
on user_addresses for select
to authenticated
using (auth.uid() = user_id);

-- Users can insert their own addresses
create policy "Users can insert their own addresses"
on user_addresses for insert
to authenticated
with check (auth.uid() = user_id);

-- Users can update their own addresses
create policy "Users can update their own addresses"
on user_addresses for update
to authenticated
using (auth.uid() = user_id);

-- Users can delete their own addresses
create policy "Users can delete their own addresses"
on user_addresses for delete
to authenticated
using (auth.uid() = user_id);

-- Function to automatically update updated_at timestamp
create or replace function update_user_addresses_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_user_addresses_updated_at
before update on user_addresses
for each row
execute function update_user_addresses_updated_at();
